project_name: terraform-provider-secrethub

builds:
  - binary: "{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386

archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: macOS
  files:
    # Only archive the binary
    - none* 

release:
  prerelease: true
