version: 2.1
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.8-alpine
    steps:
      - checkout
      - run: golangci-lint run
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - run: make testacc
    environment:
      GOPROXY: "https://proxy.golang.org"
workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - build
