version: 2.1
orbs:
  secrethub: secrethub/cli@1.0.0
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.23.8-alpine
    steps:
      - checkout
      - run: golangci-lint run
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - secrethub/install
      - checkout
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.mod" }}
      - run: go mod download
      - save_cache:
          key: go-modules-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
      - secrethub/exec:
          step-name: Run acceptance tests
          command: |
            SECRETHUB_CREDENTIAL=$TF_ACC_SECRETHUB_CREDENTIAL
            make testacc
    environment:
      GOPROXY: "https://proxy.golang.org"
      # SecretHub credential to use in the acceptance tests
      TF_ACC_SECRETHUB_CREDENTIAL: secrethub://secrethub/terraform-provider/testacc/secrethub/credential
      # AWS access key id to use in the acceptance tests
      AWS_ACCESS_KEY_ID: secrethub://secrethub/terraform-provider/testacc/aws/access_key_id
      # AWS secret access key to use in the acceptance tests
      AWS_SECRET_ACCESS_KEY: secrethub://secrethub/terraform-provider/testacc/aws/secret_access_key
workflows:
  version: 2
  pipeline:
    jobs:
      - lint
      - build
