on:
  push:
    branches:
      - release/v*

jobs:
  bump-version:
    name: Bump secrethub.ProviderVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bump version in provider_version.go
        uses: florisvdg/action-version-bump@v0.1.0
        with:
          sed: 's/^\(const ProviderVersion = "v\).*\("\)$/\1$VERSION\2/g'
          file: secrethub/provider_version.go
          author_email: bender.github@secrethub.io
